config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'admin#index'

  get 'admin', to: 'admin#index'
  scope 'admin' do
    resources :instrumentos, :partichelas, :partituras, :eventos
  end
end

app/models/instrumento.rb
class Instrumento < ActiveRecord::Base
  has_many :partichelas
end

app/controllers/instrumentos_controller.rb
class InstrumentosController < ApplicationController
  before_action :set_instrumento, only: [:show, :edit, :update, :destroy]

  # GET /instrumentos
  # GET /instrumentos.json
  def index
    @instrumentos = Instrumento.all
  end

  # GET /instrumentos/1
  # GET /instrumentos/1.json
  def show
  end

  # GET /instrumentos/new
  def new
    @instrumento = Instrumento.new
  end

  # GET /instrumentos/1/edit
  def edit
  end

  # POST /instrumentos
  # POST /instrumentos.json
  def create
    @instrumento = Instrumento.new(instrumento_params)

    respond_to do |format|
      if @instrumento.save
        format.html { redirect_to @instrumento, notice: 'Instrumento was successfully created.' }
        format.json { render :show, status: :created, location: @instrumento }
      else
        format.html { render :new }
        format.json { render json: @instrumento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instrumentos/1
  # PATCH/PUT /instrumentos/1.json
  def update
    respond_to do |format|
      if @instrumento.update(instrumento_params)
        format.html { redirect_to @instrumento, notice: 'Instrumento was successfully updated.' }
        format.json { render :show, status: :ok, location: @instrumento }
      else
        format.html { render :edit }
        format.json { render json: @instrumento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instrumentos/1
  # DELETE /instrumentos/1.json
  def destroy
    @instrumento.destroy
    respond_to do |format|
      format.html { redirect_to instrumentos_url, notice: 'Instrumento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrumento
      @instrumento = Instrumento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instrumento_params
      params.require(:instrumento).permit(:nombre)
    end
end

app/helpers/instrumentos_helper.rb
module InstrumentosHelper
end

app/views/instrumentos/_form.html.erb
<%= simple_form_for(@instrumento) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/instrumentos/edit.html.erb
<h1>Editing Instrumento</h1>

<%= render 'form' %>

<%= link_to 'Show', @instrumento %> |
<%= link_to 'Back', instrumentos_path %>

app/views/instrumentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Instrumentos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instrumentos.each do |instrumento| %>
      <tr>
        <td><%= instrumento.nombre %></td>
        <td><%= link_to 'Show', instrumento %></td>
        <td><%= link_to 'Edit', edit_instrumento_path(instrumento) %></td>
        <td><%= link_to 'Destroy', instrumento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instrumento', new_instrumento_path %>

app/views/instrumentos/new.html.erb
<h1>New Instrumento</h1>

<%= render 'form' %>

<%= link_to 'Back', instrumentos_path %>

app/views/instrumentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @instrumento.nombre %>
</p>

<%= link_to 'Edit', edit_instrumento_path(@instrumento) %> |
<%= link_to 'Back', instrumentos_path %>