config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'admin#index'

  get 'admin', to: 'admin#index'
  scope 'admin' do
    resources :instrumentos, :partichelas, :partituras, :eventos
  end
end

app/models/partitura.rb
class Partitura < ActiveRecord::Base
  has_many :eventos_partituras
  has_many :eventos, through: :eventos_partituras
  has_many :partichelas
end

app/controllers/partituras_controller.rb
class PartiturasController < ApplicationController
  before_action :set_partitura, only: [:show, :edit, :update, :destroy]

  # GET /partituras
  # GET /partituras.json
  def index
    @partituras = Partitura.all
  end

  # GET /partituras/1
  # GET /partituras/1.json
  def show
  end

  # GET /partituras/new
  def new
    @partitura = Partitura.new
  end

  # GET /partituras/1/edit
  def edit
  end

  # POST /partituras
  # POST /partituras.json
  def create
    @partitura = Partitura.new(partitura_params)

    respond_to do |format|
      if @partitura.save
        format.html { redirect_to @partitura, notice: 'Partitura was successfully created.' }
        format.json { render :show, status: :created, location: @partitura }
      else
        format.html { render :new }
        format.json { render json: @partitura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partituras/1
  # PATCH/PUT /partituras/1.json
  def update
    respond_to do |format|
      if @partitura.update(partitura_params)
        format.html { redirect_to @partitura, notice: 'Partitura was successfully updated.' }
        format.json { render :show, status: :ok, location: @partitura }
      else
        format.html { render :edit }
        format.json { render json: @partitura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partituras/1
  # DELETE /partituras/1.json
  def destroy
    @partitura.destroy
    respond_to do |format|
      format.html { redirect_to partituras_url, notice: 'Partitura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partitura
      @partitura = Partitura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partitura_params
      params.require(:partitura).permit(:titulo, :autor, :estilo)
    end
end

app/helpers/partituras_helper.rb
module PartiturasHelper
end

app/views/partituras/_form.html.erb
<%= simple_form_for(@partitura) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :titulo %>
    <%= f.input :autor %>
    <%= f.input :estilo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/partituras/edit.html.erb
<h1>Editing Partitura</h1>

<%= render 'form' %>

<%= link_to 'Show', @partitura %> |
<%= link_to 'Back', partituras_path %>

app/views/partituras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Partituras</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Autor</th>
      <th>Estilo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @partituras.each do |partitura| %>
      <tr>
        <td><%= partitura.titulo %></td>
        <td><%= partitura.autor %></td>
        <td><%= partitura.estilo %></td>
        <td><%= link_to 'Show', partitura %></td>
        <td><%= link_to 'Edit', edit_partitura_path(partitura) %></td>
        <td><%= link_to 'Destroy', partitura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Partitura', new_partitura_path %>

app/views/partituras/new.html.erb
<h1>New Partitura</h1>

<%= render 'form' %>

<%= link_to 'Back', partituras_path %>

app/views/partituras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @partitura.titulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @partitura.autor %>
</p>

<p>
  <strong>Estilo:</strong>
  <%= @partitura.estilo %>
</p>

<%= link_to 'Edit', edit_partitura_path(@partitura) %> |
<%= link_to 'Back', partituras_path %>