config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'admin#index'

  get 'admin', to: 'admin#index'
  scope 'admin' do
    resources :instrumentos, :partichelas, :partituras, :eventos
  end
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  has_many :eventos_partituras
  has_many :partituras, through: :eventos_partituras
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:nombre, :fecha)
    end
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_form.html.erb
<%= simple_form_for(@evento) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :fecha %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing Evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Eventos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.nombre %></td>
        <td><%= evento.fecha %></td>
        <td><%= link_to 'Show', evento %></td>
        <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
        <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>New Evento</h1>

<%= render 'form' %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @evento.nombre %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @evento.fecha %>
</p>

<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>