config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'admin#index'

  get 'admin', to: 'admin#index'
  scope 'admin' do
    resources :instrumentos, :partichelas, :partituras, :eventos
  end
end

app/views/layouts/_alertas.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_enlaces.html.erb
<li><%= link_to 'Eventos', eventos_path %></li>
<li><%= link_to 'Partituras', partituras_path %></li>
<li><%= link_to 'Partichelas', partichelas_path %></li>

app/views/layouts/_navbar.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1> <%= link_to 'Ateneo Musical Cartayero', root_path %></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <%= render 'layouts/enlaces' %>
    </ul>
  </section>
</nav

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Ateneo Musical Cartayero" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alertas' %>
    <div class="row fullWidth">
      <div class="large-12 columns">
        <%= yield %>
      </div>
    </div>
  </body>
</html>